name: Lint

on:
   push:
      branches:
         - "master"
   pull_request:
      branches:
         - "*"

jobs:
   lint:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v2

         - name: Setup PHP
           uses: shivammathur/setup-php@v2
           with:
              php-version: "7.1"
              extensions: intl, mbstring, mcrypt, openssl
              tools: composer

         - name: Setup problem matchers
           run: |
              echo "::add-matcher::${{ runner.tool_cache }}/php.json"

         - name: Cache Composer packages
           id: composer-cache
           uses: actions/cache@v2
           with:
              path: vendor
              key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
              restore-keys: |
                 ${{ runner.os }}-php-

         - name: Install dependencies
           if: steps.composer-cache.outputs.cache-hit != 'true'
           run: composer install --prefer-dist --no-progress --no-suggest

         - name: PHPCS check
           uses: chekalsky/phpcs-action@v1
           with:
              enable_warnings: true
              phpcs_bin_path: "./vendor/bin/phpcs"
